<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 3000          # Port exposed by the service
      targetPort: 80     # Port in the Nginx container
      nodePort: 30080    # External port on the node (must be 30000–32767)
=======
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 3000          # Port exposed by the service
      targetPort: 80     # Port in the Nginx container
      nodePort: 30080    # External port on the node (must be 30000–32767)
>>>>>>> 4c835870b8f23a00f1f5314cf5e68b7896736d8e
